services:
  mongodb:
    image: mongo:7
    container_name: communite-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: communite-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/communite?authSource=admin
      - NEXTAUTH_SECRET=mon-secret-super-securise-2026
      - NEXTAUTH_URL=http://localhost:3000
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
    networks:
      - app-network
    # SUPPRIME LA LIGNE volumes: - .:/app

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: